SIDE = 30
PLAYERS = 16
PLAYER_DISTANCE=15
MOUNTAIN_DENSITY=0.30
MOUNTAIN_LINKAGE=5
FORT_DENSITY=0.05
MIN_FORT_COST=40
MAX_FORT_COST=50
SIMULATION_LENGTH=1000
DEBUG=True # True loads bots from their classes files, without timeout on the moves. False works with the websockets as in the infrastructure and requires docker