version: "3.3"

services:
    registry_team1:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team1.registry.alberto247.xyz"
        volumes:
          - ./auth/team1:/auth
        hostname: registry_team1
    registry_team2:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team2.registry.alberto247.xyz"
        volumes:
          - ./auth/team2:/auth
        hostname: registry_team2
    registry_team3:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team3.registry.alberto247.xyz"
        volumes:
          - ./auth/team3:/auth
        hostname: registry_team3
    registry_team4:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team4.registry.alberto247.xyz"
        volumes:
          - ./auth/team4:/auth
        hostname: registry_team4
    registry_team5:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team5.registry.alberto247.xyz"
        volumes:
          - ./auth/team5:/auth
        hostname: registry_team5
    registry_team6:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team6.registry.alberto247.xyz"
        volumes:
          - ./auth/team6:/auth
        hostname: registry_team6
    registry_team7:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team7.registry.alberto247.xyz"
        volumes:
          - ./auth/team7:/auth
        hostname: registry_team7
    registry_team8:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team8.registry.alberto247.xyz"
        volumes:
          - ./auth/team8:/auth
        hostname: registry_team8
    registry_team9:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team9.registry.alberto247.xyz"
        volumes:
          - ./auth/team9:/auth
        hostname: registry_team9
    registry_team10:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team10.registry.alberto247.xyz"
        volumes:
          - ./auth/team10:/auth
        hostname: registry_team10
    registry_team11:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team11.registry.alberto247.xyz"
        volumes:
          - ./auth/team11:/auth
        hostname: registry_team11
    registry_team12:
        image: "registry:latest"
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_HTTP_HOST: "https://team12.registry.alberto247.xyz"
        volumes:
          - ./auth/team12:/auth
        hostname: registry_team12
    # registry_team13:
    #     image: "registry:latest"
    #     environment:
    #       REGISTRY_AUTH: htpasswd
    #       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #       REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #       REGISTRY_HTTP_HOST: "https://team13.registry.alberto247.xyz"
    #     volumes:
    #       - ./auth/team13:/auth
    #     hostname: registry_team13
    # registry_team14:
    #     image: "registry:latest"
    #     environment:
    #       REGISTRY_AUTH: htpasswd
    #       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #       REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #       REGISTRY_HTTP_HOST: "https://team14.registry.alberto247.xyz"
    #     volumes:
    #       - ./auth/team14:/auth
    #     hostname: registry_team14
    # registry_team15:
    #     image: "registry:latest"
    #     environment:
    #       REGISTRY_AUTH: htpasswd
    #       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #       REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #       REGISTRY_HTTP_HOST: "https://team15.registry.alberto247.xyz"
    #     volumes:
    #       - ./auth/team15:/auth
    #     hostname: registry_team15
    # registry_team16:
    #     image: "registry:latest"
    #     environment:
    #       REGISTRY_AUTH: htpasswd
    #       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #       REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #       REGISTRY_HTTP_HOST: "https://team16.registry.alberto247.xyz"
    #     volumes:
    #       - ./auth/team16:/auth
    #     hostname: registry_team16
    
    backend:
        build: "./webbackend"
        volumes: 
          - "./results:/results"
        hostname: "backend"
    
    scoreboard:
        build: "./scoreboard-server"
        volumes: 
          - "./results:/results"
        hostname: "scoreboard"
    
    frontend:
        image: httpd:latest
        volumes:
        - ./webfrontend/build:/usr/local/apache2/htdocs

    nginx:
        image: nginx:alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - /etc/letsencrypt:/etc/letsencrypt
          - ./auth/scoreboard.password:/etc/apache2/.htpasswd
        ports:
          - "443:443"
        depends_on:
          - registry_team1
          - registry_team2
          - registry_team3
          - registry_team4
          - registry_team5
          - registry_team6
          - registry_team7
          - registry_team8
          - registry_team9
          - registry_team10
          - registry_team11
          - registry_team12
          # - registry_team13
          # - registry_team14
          # - registry_team15
          # - registry_team16
